### PR TITLE
Migration to Sharp

### PR DESCRIPTION
**Pull request by casungo**
Since the migration to wasm gave me other errors, I followed the hint in #8 and implemented Sharp. Lot of room to further improve it by allowing users to choose image output format, additional settings ecc...
Maybe will do it after this gets pushed
PS: i dont know how to do a changeset (or how to do it correctly), sorry :/

### CODE REVIEW

**Review by florian-lefebvre — APPROVED** [review]
Awesome contribution thank you! I thought Sharp could not do that.

I made some updates to your PR, please try it again locally and let me know if that works! (and feel free to review the PR)

**Comment by florian-lefebvre** [comment]
Apparently there's a wasm build of sharp. Wanna try that?

**Comment by casungo** [comment]
Honestly I don't think it's going to resolve the issue. In the future I might investigate on why this is happening with CF pages, but right now I don't have the time, sorry :(

**Comment by florian-lefebvre** [comment]
np! still going to ship this since it doesn't require an integration anymore

**Pull request merged**
